version: '3.1'
services:
    php-fpm:
        build: phpdocker/php-fpm
        container_name: redoc_main_php
        working_dir: /var/www/redoc.tech/app
        volumes:
            - './app:/var/www/redoc.tech/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        ports:
            - '9002:9000'

    mariadb:
        image: 'mariadb:10.8'
        volumes:
            - './.docker/mariadb/data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=cs_root
            - MYSQL_DATABASE=cs_db
            - MYSQL_USER=cs_azk
            - MYSQL_PASSWORD=cs_aziztd
