name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            cd /var/www/cv.redoc.tech
            git pull
            docker compose down
            docker compose up -d
            sleep 15
            docker compose exec php-fpm php bin/console d:m:m --no-interaction
            composer dump-env dev
            docker compose exec php-fpm php bin/console c:c
            composer dump-env prod
            docker compose exec php-fpm php bin/console c:c